baseurl         = "/post"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
summaryLength   = 50
#SectionPagesMenu = "main"
enableRobotsTXT = true
canonifyURLs = true

[params]
  title       = "The Connected Home"
  subtitle    = "I should probably stop changing things"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = "UA-3086522-15"
  customCSS = []
  RSSLink = ""

  twitterName = "kebabman"
  githubName = "kebabmane"

  author = "Rhys"
  authorAvatar = "img/bio-photo.jpg"
  authorLocation = "Melbourne Australia"
  authorDescription = "Lazy Gen-Y type, first computer experience was pressing the turbo button a 386 and wondering why nothing happened."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]